src/apps/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'apps'

urlpatterns = [
	# This URL can be used to make use of SearchFilterForm and filter 
	# search results based on User inputs. Refer forms.py and uncomment this when required.
    # path('tag/', views.tagSearch, name='tagSearch'),
    path('<slug:name>/', views.appPage, name='appPage'),
    path('tag/all/', views.tagSearch, name='allApps'),
    path('tag/<slug:name>/', views.tagSearch, name='tagSearch'),
    path('feedback/<int:num>/', views.feedback, name='feedback'),
]

src/download/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'download'

urlpatterns = [
    path(
        'stats/',
        views.all_stats,
        name='all_stats'),
    path(
        'stats/<slug:name>',
        views.app_stats,
        name='app_stats'),
]

src/apps/templates/app_button.html
{% load static %}

<div class="app_button filter all {{app.app_type}}"
  order_index="{{ order_index }}"
  fullname="{{ app.title }}"
  votes="{{ app.votes }}"
  latest_release_date="{{ app.latest_release_date.isoformat }}"
  onClick="window.location='/app/{{ app.name }}';">

  <a href="/app/{{ app.name }}">
    <div class="partial all {{app.app_type}}">
      <table border="0" width="100%">
        <tr valign="top">
          <td width="64" rowspan="2">
            <div class="app_icon">
              <img src="/media/{{ app.icon }}"/>
            </div>
          </td>
          <td align="left">
            <h5>{{ app.title }}</h5>
          </td>
        </tr>
        <tr valign="top">
          <td valign="top">
            <div class="description">
              {% if app.abstract %}
                {{ app.abstract }}
              {% endif %}
            </div>
          </td>
        </tr>
      </table>
    </div>

    <div class="full">
      <table border="0" width="100%">
        <tr valign="top">
          <td width="64" rowspan="2">
            <div class="app_icon">
              <img src="/media/{{ app.icon }}"/>
            </div>
          </td>
          <td align="left">
            <h5>{{ app.title }}</h5>
          </td>
        </tr>
        <tr valign="top">
          <td>
            <div class="description">
              {% if app.abstract %}
                {{ app.abstract }}
              {% endif %}
            </div>
          </td>
        </tr>
        <tr>
          <td></td>
          <td valign="baseline">
            <div class="stars">
              <i class="stars-empty icon-cy-stars-empty"></i>
              <i class="stars-full icon-cy-stars-filled" style="width: {{ app.stars_percentage }}%"></i>
            </div>
            <span class="votes">
              ({{ app.votes }})
            </span>
          </td>
        </tr>
      </table>
    </div>
  </a>
</div>

src/apps/templates/app_buttons.html
{% load app_buttons %}

<div class="span4" id="left">
  {% for app in apps %}
    {% if not forloop.counter|divisibleby:2 %}
      {% app_button app forloop.counter %}
    {% endif %}
  {% endfor %}
</div>
<div class="span4" id="right">
  {% for app in apps %}
    {% if forloop.counter|divisibleby:2 %}
      {% app_button app forloop.counter %}
    {% endif %}
  {% endfor %}
</div>

<script>
$(document).ready(function () {
  $(".filter-button").click(function () {
    var value = $(this).attr('data-filter');
    if (value == "all") {
      $(".text").remove();
      $(".filter").not('.' + value).hide('3000');
      $('.filter').filter('.' + value).show('3000');
    }
    else if(value == "F") {
      $(".text").remove();
      $(".filter").not('.' + value).hide('3000');
      $('.filter').filter('.' + value).show('3000');

      if($(".filter").not('.' + value).length == $(".filter").filter('.' + "all").length) {
          $("#left").append("<p class=\"text\">No Apps found</p>");
      }
    }
    else if (value == "M") {
      $(".text").remove();
      $(".filter").not('.' + value).hide('3000');
      $('.filter').filter('.' + value).show('3000');

      if($(".filter").not('.' + value).length == $(".filter").filter('.' + "all").length) {
          $("#left").append("<p class=\"text\">No Apps found</p>");
      }
    }
  });
});
</script>

src/apps/templates/apps.html
{% extends "nav_panel.html" %}
{% load static %}
{% load app_buttons %}

{% block title %}
 - All Apps
{% endblock %}

{% block main %}
  {% list_of_apps apps %}
{% endblock %}

src/apps/templates/apps_author.html
{% extends "base.html" %}
{% load app_buttons %}
{% load static %}

{% block title %}
- {{ author_name }}
{% endblock %}

{% block more_head %}
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/nav_panel.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_button.css"/>
  <link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css"/>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span8">
            <div class="page-header">
                <h1>{{ author_name }}</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <h2 style="margin-bottom: 1em;">Apps</h2>
        </div>
    </div>
    <div class="row">
        <div class="span12">
            {% app_buttons apps %}
        </div>
    </div>
{% endblock %}

src/apps/templates/apps_tag.html
{% extends "nav_panel.html" %}
{% load app_buttons %}

{% block title %}
- {{ tag.name }} category
{% endblock %}

{% block main %}
  <div class="row" style="margin-bottom: 2em;">
    <div class="span12">
      <h1>{{ tag.name|capfirst }}</h1>
      <!--p>
      <a href='"{#{ tag.name }#}"' target="_blank">
        <i class="icon-comment"></i>
        Search for posts about {#{ tag.name }#} &rarr;
      </a>
      </p>
      <p>
      <a href="" target="_blank">
        <i class="icon-question-sign"></i>
        Ask a question about {#{ tag.name }#} &rarr;
      </a>
      </p-->
      {% if not apps %}
       <p>
        No results found for {{ tag.name }}
       </p>
      {% endif %}
    </div>
  </div>
  {% list_of_apps apps %}
{% endblock %}

src/apps/templates/comment.html
{% extends "base.html" %}

{% load material_form %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Feedback{% endblock %}

{% block container %}
<main>
<div class="container form-box">
  <div class="center">
    <h2>Submit Feedback</h2>
  </div>
  <form method="POST">
      {% csrf_token %}
      {% form form=form %}{% endform %}
      <button type="submit" name="_submit" class="btn">Submit</button>
  </form>
</div>
</main>
{% endblock container %}

src/apps/templates/landing.html
{% extends "nav_panel.html" %}
{% load app_buttons %}

{% block main %}
  <style type="text/css">
    h2 { margin-bottom: 0.5em; }
    .span4 { margin-bottom: 1em; }
  </style>
  <div class="row">
    <div class="span4"><h2>Your Apps</h2></div>
  </div>
  <div class="row">{% app_buttons your_apps %}</div>
  <a style="display: none;" href="/media/fu.txt">fu skript kiddiez</a>
{% endblock %}

src/apps/templates/list_of_apps.html
{% load static %}
{% load app_buttons %}

{% if apps_with_releases %}
  <div class="row" style="margin-bottom: 4em;" id="apps-with-releases">
    <div class="span8">
      <div class="row">
        <div class="span4" align="left">
          <table style="margin-bottom: 1em;">
            <tr>
              <td><span style="margin-right: 0.5em;">Sort by</span></td>
              <td>
                <span id="sort_app_buttons" class="btn-group">
                {% for button_name, attr_name, attr_type in sort_criteria %}
                <button class="btn btn-small" attr_name="{{ attr_name }}" attr_type="{{ attr_type }}">
                  <span class="title">{{ button_name }}</span>
                  <span class="triangle"></span>
                </button>
                {% endfor %}
                </span>
              </td>
            </tr>
          </table>
        </div>
        <div class="span4" align="right">
          <table style="margin-bottom: 1em;">
            <tr>
              <td><span style="margin-right: 0.5em;">Filter by</span></td>
              <td>
                <span class="btn-group">
                <button class="btn btn-small filter-button" data-filter="all">
                  <span class="title">All</span>
                </button>
                <button class="btn btn-small filter-button" data-filter="F">
                  <span class="title">Fork</span>
                </button>
                <button class="btn btn-small filter-button" data-filter="M">
                  <span class="title">Modules</span>
                </button>
                </span>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    {% app_buttons apps_with_releases %}
  </div>
  <script type="text/javascript" src="{% get_static_prefix %}apps/js/sort_app_buttons.js"></script>
  <script type="text/javascript">
    $(function() {
        SortAppButtons.init_sort_buttons($('#apps-with-releases'));
    });
  </script>
{% endif %}

{# % if apps_without_releases % #}
  <!--div class="row">
    {% app_buttons apps_without_releases %}
  </div-->
{# % endif % #}

src/apps/templates/page.html
{% extends "base.html" %}
{% load static %}
{% load ratings %}

{% block more_head %}
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_page.css" />
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css" />
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/jquery.timeago.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Converter.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/lib/js/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/setup_ajax_for_csrf.js"></script>
<script type="text/javascript" src="{% get_static_prefix %}common/js/markdown_util.js"></script>
{% endblock %}

{% block title %}- {{ app.title }}{% endblock %}

{% block content %}
{% csrf_token %}

{# "Go back to" link #}
{% if go_back_to_title %}
<div class="row">
	<div class="span8" style="margin-bottom: 2em;">
		<a href="{{ go_back_to_url }}">&larr; Go back to {% autoescape off %}{{ go_back_to_title }}{% endautoescape %}</a>
	</div>
</div>
{% endif %}

{# App header #}
<div class="row">
	{# App icon #}
	<div class="span1" style="line-height: 64px;">
		<img style="vertical-align: middle;" src="/media/{{ app.icon }}"/>
	</div>
	{# App name and description #}
	<div class="span7">
		<h2 id="app-name">
			{{ app.title }}
		</h2>
		{% if app.abstract %}<b>{{ app.abstract }}</b>{% endif %}
	</div>

	{# Editor menu #}
	{% if user.is_staff or user in editors %}
	<div class="span3 offset1">
		<div class="btn-group pull-right">
			<a class="btn btn-warning dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="icon-pencil icon-white"></i>
				Editor Actions
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu pull-right">
				<li><a href="/backend/edit/{{ app.id }}">Edit this page</a></li>
				<li><a href="/backend/create/release/{{ app.id }}">Submit a new release</a></li>
				<li><a href="/backend/screenshots/{{ app.id }}">Add a new screenshot</a></li>
				<li><a href="/backend/development/{{ app.id }}">Add/Edit Development Version Details</a></li>
				<li class="divider"></li>
				<!--li><a data-toggle="modal" href="#delete_ratings_modal">Delete all ratings</a></li-->
				<li><a href="/backend/details/{{ app.id }}">Edit Details</a></li>
				<li><a href="/backend/installation/{{ app.id }}">Add/Edit Installation</a></li>
				<li><a href="/backend/maintenance/{{ app.id }}">Add/Edit Maintenance</a></li>
				<li><a href="/backend/download/{{ app.id }}">Add/Edit Download</a></li>
			</ul>
		</div>
	</div>
	{% endif %}
	{# End editor menu #}
</div>
{# End app header #}

{# App usage info (ratings, downloads) #}
<div class="row">
	<div class="span12" id="app-usage-info">
		{# Ratings #}
		<!-- <div class="rating-stars" data-placement="bottom" data-title="Rate this app! <a class='close' style='margin-left: 0.5em;'>&times;</a>" data-html="true">
			<i class="rating-stars-empty icon-cy-stars-empty"></i>
			<i class="rating-stars-filled icon-cy-stars-filled" style="width: {{ app.stars_percentage|escapejs }}%;"></i>
			<span class="rating-spacer"></span>
		</div>
		<span id="rating-count">({{ app.votes|escapejs }})</span> -->
		<div class="row">
			<div class="span4">
				{% ratings app %}
			</div>
		{# End Ratings #}
		{# Downloads #}
			<div class="span4" style="margin-top: 8px;">
				{% if app.has_releases %}
				<span class="app-usage-info-divider"></span>
					<a href="{% url 'download:app_stats' app.name %}" target="_blank">
					{{ app.downloads }} downloads</a>
				{% endif %}
		{# End Downloads #}
				<span class="app-usage-info-divider"></span>

				{% if app.coderepo %}
				<a href="{{ app.coderepo }}" target="_blank">
					<img src="{% get_static_prefix %}apps/img/open-source.png" class="has-tooltip" data-toggle="tooltip" data-title="This app is open source.">
				</a>
				{% endif %}
			</div>
		{# end badges #}
	</div>
</div>
{# End app usage info #}

{# Main app page content #}
<div class="row">
	<div class="span8">
		{# Tabs #}
		<ul id="cy-app-info-tabs" class="nav nav-tabs">
			<li class="active">
				<a href="#cy-app-details-tab" data-toggle="tab">
					<b>Details</b>
				</a>
			</li>
			{% if app.has_releases %}
			<li>
				<a href="#cy-app-releases-tab" data-toggle="tab">
					<b>Release History</b>
				</a>
			</li>
			{% endif %}
			{% if app.installation %}
			<li>
				<a href="#cy-app-installation-tab" data-toggle="tab">
					<b>Installation</b>
				</a>
			</li>
			{% endif %}
			{% if app.maintenance %}
			<li>
				<a href="#cy-app-maintenance-tab" data-toggle="tab">
					<b>Maintenance</b>
				</a>
			</li>
			{% endif %}
			{% if app.development %}
			<li>
				<a href="#cy-app-development-tab" data-toggle="tab">
					<b>Development</b>
				</a>
			</li>
			{% endif %}
		</ul>
		{# End Tabs #}

		{# Tab content #}
		<div class="tab-content">
			{# Details tab #}
			<div class="tab-pane active" id="cy-app-details-tab">
				{# Categories #}
				{% if tags %}
				<div class="row">
					<div class="span8">
						Categories:
						{% for tag in tags %}
						<a class="link" href="/app/tag/{{ tag.identity }}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
						{% endfor %}
					</div>
				</div>
				{% endif %}
				{# End Categories #}

				{# Screenshots #}
				{% if screenshots %}
				<div class="row">
					<div class="span8" id="cy-app-screenshots">
						{% for screenshot in screenshots %}
						<a href="/media/{{ screenshot.screenshot }}" target="_blank">
							<img src="/media/{{ screenshot.thumbnail }}"/>
						</a>
						{% if user.is_staff or user in editors %}
						<a class="btn btn-warning" href="/backend/screenshotdelete/{{ screenshot.id }}" style="margin-bottom:120px">
							x
						</a>
						{% endif %}
						{% endfor %}
					</div>
				</div>
				{% endif %}
				{# End Screenshots #}

				{# Details #}
				{% if app.description %}
				<div class="row">
					<div class="span8" id="cy-app-details-md">{{ app.description|safe }}</div>
				</div>
				{% endif %}
				{# End Details #}

			</div>
			{# End Details tab #}

			{# Releases tab #}
			{% if app.has_releases %}
			<div class="tab-pane" id="cy-app-releases-tab">
				{% for release in releases %}
				<div class="row">
					<div class="span8">
						{# Release version #}
						<h4>
							<a href="{{ release.url }}">
								{{ release.version }}
							</a>
						</h4>
						{# End Release version #}

						{# Works with #}
						{% if release.require %}
						<p>
							<strong>Works with</strong>
							{{ release.require }}
						</p>
						{% endif %}
						{# End Works with #}

						{% if release.notes %}
						<p><strong>Release Notes</strong></p>
						<div class="cy-app-release-notes">{{ release.notes }}</div>
						{% endif %}

						{% if release.filename %}
						<strong>Bakefile : </strong>
						<a href="/media/{{ release.filename }}">Link</a>
						<br><br>
						{% endif %}
						{% if user.is_staff or user in editors %}
						<a class="btn btn-warning" href="/backend/edit/release/{{ release.id }}">
							Edit Release
						</a>
						<a class="btn btn-warning" href="/backend/releasedelete/{{ release.id }}">
							Delete Release
						</a>
						{% endif %}
						{# End Release #}
						<hr>
					</div>
				</div>
				{% endfor %} {# end looping thru each release #}
			</div>
			{% endif %}
			{# End Releases tab #}

			{# Installation tab #}
			{% if app.installation %}
			<div class="tab-pane" id="cy-app-installation-tab">
				<div class="row">
					<div class="span8">
							<h1>Dependencies</h1>
							 <div class="row">
								<div class="span4">
									{% if compulsory_dependency %}
										<h4>Compulsory</h4>
										<ul>
										{% for cd in compulsory_dependency %}
											<li>{{ cd }}</li>
										{% endfor %}
										</ul>
									{% endif %}		
								</div>
								<div class="span4">
									{% if optional_dependency %}
										<h4>Optional</h4>
										<ul>
										{% for od in optional_dependency %}
											<li>{{ od }}</li>
										{% endfor %}
										</ul>
									{% endif %}
								</div>
							</div> 
							

							

							{% if compulsory_dependency or optional_dependency %}
							<hr>
							{% endif %}
						<div class="cy-app-release-notes">{{ app.installation.installation|safe }}</div>
						<hr>
					</div>
				</div>
			</div>
			{% endif %}
			{# End Installation tab #}

			{# Maintenance tab #}
			{% if app.maintenance %}
			<div class="tab-pane" id="cy-app-maintenance-tab">
				<div class="row">
					<div class="span8">
						<div class="cy-app-release-notes">{{ app.maintenance.notes|safe }}</div>
						<hr>
					</div>
				</div>
			</div>
			{% endif %}
			{# End Maintenance tab #}

			{# Development tab #}
			{% if app.development %}
			<div class="tab-pane" id="cy-app-development-tab">
				<div class="row">
					<div class="span8">
						<div class="cy-app-release-notes">{{ app.development.notes|safe }}</div>
					</div>
				</div>
				{% if app.development.filename %}
					<b>Bakefile : </b><a href="/media/{{ app.development.filename }}/">Link</a>
				{% endif %}
				<hr>
			</div>
			{% endif %}
			{# End Maintenance tab #}
		</div>
	</div>
	{# End Tab content #}

	{# Right-hand panels #}
	<div class="span3 offset1">

		{# Notify if App is Fork/Module #}
		<div class="well">
			{% if app.app_type == 'F' %}
			<p>This ns-3 extension is a <strong>separately maintained fork</strong>.</p>
			{% else %}
			<p>This ns-3 extension is one or more <strong>contributed modules</strong>.</p>
			{% endif %}
		</div>
		{# End App Notification #}

		{# Download panel #}
		{% if app.download %}
		<div class="well">
			<button class="btn btn-large btn-block" id="cy-app-install-btn">
				{% if app.app_type == 'F' %}
				<i></i> {# <-- download button icon will go here #}
				<h4>Visit</h4> {# <-- download button text will go here #}
				{% else %}
				<i></i>
				<h4>Download</h4>
				{% endif %}
			</button>
			<p><strong>Version</strong> {{ latest.version }}</p>
			<p><strong>Released</strong> {{ latest.date }}</p>
			{% if latest.require %}<p><strong>Works with</strong> <a href="{{ latest.require.url }}" target="_blank">{{ latest.require }}</a></p>{% endif %}
			{% if app.app_type == 'M' %}
			{% if latest.filename %}<p><strong>Bake</strong> <a href="/media/{{ latest.filename }}" target="_blank">bakeconf.xml</a>{% endif %}
			{% endif %}
		</div>
		{# end Download panel #}

		{# in case there are no downloads... #}
		{% else %}
		<div class="alert alert-error">
			No download available.
		</div>
		{% endif %}
		{# end no downloads #}

		{# app resources #}
		<div class="well">
			<ul class="nav nav-list">
				<li class="nav-header">
					Resources
				</li>
				{% if app.mailing_list %}
				<li>
					<a href="{{ app.mailing_list}}" target="_blank">
						<i class="icon-question-sign"></i>
						Ask a question
					</a>
				</li>
				{% endif %}

				{% if app.issue %}
				<li>
					<a href="{{ app.issue }}" target="_blank">
					<i class="icon-question-sign"></i>
					Report a Bug
				</a></li>
				{% endif %}

				<li class="divider"></li>

				{% if app.website %}
				<li><a href="{{ app.website }}" target="_blank">
					<i class="icon-home"></i> Website
				</a></li>
				{% endif %}

				{% if app.documentation %}
				<li><a href="{{ app.documentation }}" target="_blank">
					<i class="icon-book"></i> Documentation
				</a></li>
				{% endif %}

				{% if app.coderepo %}
				<li><a href="{{ app.coderepo }}" target="_blank">
					<i class="icon-list-alt"></i> Code Repository
				</a></li>
				{% endif %}

				{% if app.contact %}
				<li><a href="mailto:{{ app.contact }}" target="_blank">
					<i class="icon-envelope"></i> E-mail
				</a></li>
				{% endif %}
			</ul>
		</div>
		{# end app resources #}
	</div>
	{# end right-hand panels #}
</div>
{# end main app page content #}

{# Delete all ratings modal dialog #}
<div class="modal hide fade in" id="delete_ratings_modal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>Delete All Ratings</h3>
	</div>
	<div class="modal-body">
		Are you sure you want to delete all of your app's ratings?
	</div>
	<div class="modal-footer">
		<form target="" method="post" style="margin: 0;">
			{% csrf_token %}
			<input type="hidden" name="action" value="ratings_delete_all">
			<a href="#" class="btn" data-dismiss="modal">Cancel</a>
			<input type="submit" class="btn btn-danger" value="Yes, I'm Sure">
		</form>
	</div>
</div>
{# End modal dialog #}

{# Vote popover content #}
<script type="text/html" id="rate-popover-content">
<div class="rating-stars">
	<i class="rating-stars-empty icon-cy-stars-empty"></i>
	<i class="rating-stars-filled icon-cy-stars-filled" style="width: 100%;"></i>
	<span class="rating-spacer"></span>
</div>
<button class="btn btn-mini" id="rate-btn">Rate it <span id="rating">5</span> star(s)</button>
</script>
{# End vote popover content #}

<script type="text/javascript" src="{% get_static_prefix %}apps/js/app_page.js"></script>

<script type="text/javascript">
$('.has-tooltip').tooltip();
{% if app.has_releases %}
AppPage.setup_install("{{ app.name|escapejs }}",
	"{{ app.fullname|escapejs }}",
	"{{ app.download.download_link }}",
	"{{ latest.version }}",
	"");
{% endif %}

{% if app.details %}
AppPage.setup_details();
{% endif %}

AppPage.setup_stars();

AppPage.setup_release_notes();
</script>
{% endblock %}